### ISSUE TITLE
readme incomplete

### ISSUE THREAD

**Issue by ouya99** [ANDLABS-Git/AndlabsAndroidUtils#1]
Please specify what AndroidUtils contains.

**Comment by jborchardt** [comment]
Please see https://github.com/ANDLABS-Git/AndroidUtils/blob/master/README.md

2013/9/26 java99 notifications@github.com

> Please specify what AndroidUtils contains.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ANDLABS-Git/AndroidUtils/issues/1
> .

## 

_Johannes Borchardt_
Geschäftsführender Gesellschafter (CEO)

ANDLABS OHG
Krumpperstr. 22
82362 Weilheim, Germany

Tel.: +49 (0) 176 83 00 11 04
E-Mail: borchardt@andlabs.com
www.andlabs.com

Amtsgericht München, HRA 100084
Geschäftsführung: Johannes Borchardt, Florian Detig, Lukas Jarosch

This message is intended only for the use of the addressee and may contain
information that is privileged and/or confidential. If you are not the
intended recipient, any review, retransmission, dissemination,
distribution, forwarding, or other use of, or taking of any action in
reliance upon,  this communication is prohibited. If you have received this
communication in error, please erase all copies of the message and its
attachments and notify us immediately.

**Comment by ouya99** [comment]
Done and fixed
