### ISSUE TITLE
Logging file L.java has something wrong

### ISSUE THREAD

**Issue by laomo** [ANDLABS-Git/AndlabsAndroidUtils#5]
https://github.com/ANDLABS-Git/AndlabsAndroidUtils/blob/master/library/src/com/andlabs/androidutils/logging/L.java#L106

This line should be:

message = (args == null || args.length == 0) ? s1.toString(): String.format(s1.toString(), args);
1. args maybe not null, but length ==0
2. when s1 can be Integer,can't cast to String

**Comment by dkokic** [comment]
I hope you don't believe that `s1.toString()` is doing casting ;-)

**Comment by laomo** [comment]
> I hope you don't believe that s1.toString() is doing casting ;-)

yes,but there shuld be something deal with and don't throw cast exception
